apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
    - name: hello
      image: gauthambappalige12/hello:tagversion
      ports:
        - containerPort: 8080