  apiVersion: v1
  kind: Service
  metadata:
    name: helloworld
  spec:
    ports:
      - port: 80
        nodePort: 30008
        targetPort: 8080
        protocol: TCP
    selector:
      app: helloworld
    type: NodePort